services:
  postgres:
    container_name: postgres
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: alexander
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - ./.docker/postgres/database:/var/lib/postgresql/data
